# Generated by Django 5.2.1 on 2026-05-19 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=90, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Categorías',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Prompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=180)),
                ('descripcion', models.TextField(help_text='Para qué sirve el prompt y cómo se usa en clase.')),
                ('contenido', models.TextField(help_text='Texto del prompt tal como se envía a la IA.')),
                ('asignatura', models.CharField(blank=True, max_length=120)),
                ('nivel', models.CharField(choices=[('basica', 'Educación básica'), ('media', 'Educación media'), ('universitario', 'Universitario'), ('transversal', 'Transversal')], default='transversal', max_length=20)),
                ('tags', models.CharField(blank=True, help_text='Lista separada por comas. Ej: rúbrica, evaluación, escritura', max_length=255)),
                ('autor', models.CharField(default='Anónimo', max_length=120)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente de revisión'), ('aprobado', 'Aprobado'), ('destacado', 'Destacado por la comunidad'), ('rechazado', 'Rechazado')], default='pendiente', max_length=20)),
                ('likes', models.PositiveIntegerField(default=0)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prompts', to='biblioteca.categoria')),
            ],
            options={
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autor', models.CharField(default='Anónimo', max_length=120)),
                ('texto', models.TextField()),
                ('contenido_sugerido', models.TextField(blank=True, help_text='Versión mejorada del prompt propuesta por la comunidad.')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('prompt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='biblioteca.prompt')),
            ],
            options={
                'ordering': ['creado_en'],
            },
        ),
        migrations.AddIndex(
            model_name='prompt',
            index=models.Index(fields=['estado', '-creado_en'], name='biblioteca__estado_3bfc31_idx'),
        ),
    ]
