# Generated by Django 5.2.1 on 2026-05-19 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Discussion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('body', models.TextField()),
                ('author', models.CharField(max_length=120)),
                ('topic', models.CharField(max_length=90)),
                ('replies', models.PositiveIntegerField(default=0)),
                ('last_activity', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-last_activity'],
            },
        ),
        migrations.CreateModel(
            name='PromptActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('summary', models.TextField()),
                ('prompt', models.TextField()),
                ('subject', models.CharField(max_length=90)),
                ('level', models.CharField(max_length=90)),
                ('author', models.CharField(max_length=120)),
                ('status', models.CharField(choices=[('curated', 'Curado'), ('review', 'En revision'), ('draft', 'Borrador')], default='review', max_length=20)),
                ('tags', models.CharField(blank=True, max_length=220)),
                ('likes', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('description', models.TextField()),
                ('resource_type', models.CharField(choices=[('course', 'Curso'), ('program', 'Programa'), ('site', 'Sitio'), ('guide', 'Guia')], max_length=20)),
                ('url', models.URLField(blank=True)),
                ('source', models.CharField(max_length=120)),
                ('featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-featured', 'title'],
            },
        ),
    ]
