# Generated by Django 5.2.1 on 2026-05-19 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='image_url',
            field=models.URLField(blank=True),
        ),
    ]
