# Generated by Django 5.2.1 on 2026-05-19 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_resource_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='event_date',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='resource',
            name='label',
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
