# Generated by Django 5.2.1 on 2026-05-19 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0003_resource_event_date_resource_label'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resource',
            options={'ordering': ['-sort_order', '-featured', 'title']},
        ),
        migrations.AddField(
            model_name='resource',
            name='sort_order',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
